<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en">
<context>
    <name>EditableGeoCsv</name>
    <message>
        <location filename="geocsv_plugin.py" line="57"/>
        <source>Add GeoCSV layer</source>
        <translation>Add GeoCSV layer</translation>
    </message>
    <message>
        <location filename="geocsv_plugin.py" line="64"/>
        <source>Editable GeoCSV</source>
        <translation>Editable GeoCSV</translation>
    </message>
</context>
<context>
    <name>GeoCsvNewController</name>
    <message>
        <location filename="geocsv_controller.py" line="122"/>
        <source>invalid file path</source>
        <translation>invalid file path</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="163"/>
        <source>unknown csvt attribute: {}</source>
        <translation>unknown csvt attribute: {}</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="165"/>
        <source>csv&lt;-&gt;csvt missmatch</source>
        <translation>Notice: csv&lt;-&gt;csvt missmatch</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="167"/>
        <source>csvt geometry type exception</source>
        <translation>csvt geometry type exception</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="169"/>
        <source>no csvt file found</source>
        <translation>Notice: No csvt file found</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="193"/>
        <source>error while loading csv</source>
        <translation>error while loading csv</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="183"/>
        <source>error in geometry selection</source>
        <translation>error in geometry selection</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="78"/>
        <source>GeoCSV Layer created</source>
        <translation>GeoCSV layer created</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="78"/>
        <source>The layer &quot;{}&quot; was created successfully.</source>
        <translation>The layer &quot;{}&quot; was created successfully.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="108"/>
        <source>Open GeoCSV File</source>
        <translation>Open GeoCSV file</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="108"/>
        <source>Files (*.csv *.tsv)</source>
        <translation>Files (*.csv *.tsv)</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="294"/>
        <source>CSVT File Error</source>
        <translation>CSVT file error</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="84"/>
        <source>The csvt file couldn&apos;t be updated on disk.</source>
        <translation>The csvt file couldn&apos;t be updated on disk.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="294"/>
        <source>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</source>
        <translation>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="125"/>
        <source>invalid delimiter</source>
        <translation>Unknown delimiter found in csv file.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="137"/>
        <source>not utf8 encoded</source>
        <translation>The csv file is not UTF-8 encoded.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="149"/>
        <source>error in converting</source>
        <translation>The conversion wasn&apos;t successful. Please convert to UTF-8 manually and try again.</translation>
    </message>
</context>
<context>
    <name>GeoCsvReconnectController</name>
    <message>
        <location filename="geocsv_controller.py" line="269"/>
        <source>Couldn&apos;t automatically restore csv layer &quot;{}&quot;</source>
        <translation>Couldn&apos;t automatically restore csv layer &quot;{}&quot;</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="267"/>
        <source>GeoCSV Layer reconnected</source>
        <translation>GeoCSV layer reconnected</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="267"/>
        <source>Layer &quot;{}&quot; is successfully reconnected</source>
        <translation>Layer &quot;{}&quot; is successfully reconnected.</translation>
    </message>
</context>
<context>
    <name>VectorLayerController</name>
    <message>
        <location filename="geocsv_controller.py" line="281"/>
        <source>CSV File updated</source>
        <translation>CSV file updated</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="281"/>
        <source>Changes to layer &quot;{}&quot; successfully stored in csv file.</source>
        <translation>Changes to layer &quot;{}&quot; successfully stored in csv file.</translation>
    </message>
</context>
<context>
    <name>VectorLayerSaveConflictController</name>
    <message>
        <location filename="geocsv_controller.py" line="357"/>
        <source>Invalid path</source>
        <translation>Invalid path</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="357"/>
        <source>An error occured while trying to save file on new location. Please try again.</source>
        <translation>An error occured while trying to save file to new location. Please try again.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="306"/>
        <source>CSVT file could not be updated</source>
        <translation>CSVT file could not be updated</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="306"/>
        <source>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</source>
        <translation>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="301"/>
        <source>Error while updating attributes happend</source>
        <translation>Error while updating attributes happend</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="301"/>
        <source>An error occured while trying to update the attributes list. Nothing has been stored on disk.</source>
        <translation>An error occured while trying to update the attributes list. Nothing has been stored on disk.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="311"/>
        <source>Geometry index violation</source>
        <translation>Geometry index violation</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="311"/>
        <source>You tried to delete an attribute which is providing geometry information. The change will not be saved to disk.</source>
        <translation>You deleted an attribute that was providing geometry information. This can lead to unpredictable problems. Please exit edit mode without saving your changes.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="348"/>
        <source>Files (*.csv *.tsv)</source>
        <translation>Files (*.csv *.tsv)</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="355"/>
        <source>CSV File updated</source>
        <translation>CSV file updated</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="355"/>
        <source>Changes to layer &quot;{}&quot; successfully stored in csv file.</source>
        <translation>Changes to layer &quot;{}&quot; successfully stored in csv file.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="348"/>
        <source>Save File</source>
        <translation>Save File</translation>
    </message>
</context>
<context>
    <name>geocsvDialogNew</name>
    <message>
        <location filename="geocsv_dialog_new.ui" line="14"/>
        <source>GeoCSV Editor</source>
        <translation>Add new GeoCSV layer</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="29"/>
        <source>Retry</source>
        <translation>Retry</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="68"/>
        <source>Cancel</source>
        <translation>Cancel</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="43"/>
        <source>Save As</source>
        <translation>Save As...</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="59"/>
        <source>Error: The csv file could not be saved. File Lock?</source>
        <translation>The action can&apos;t be completed because the file couldn&apos;t be found or is currently in use by another program.</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="29"/>
        <source>Dateiname</source>
        <translation>Filename</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="46"/>
        <source>Durchsuchen...</source>
        <translation>Browse...</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="78"/>
        <source>Ok</source>
        <translation>OK</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="122"/>
        <source>WKT Field</source>
        <translation>WKT Field</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="136"/>
        <source>Point (Easting/Northing)</source>
        <translation>Easting/Northing (Point)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="155"/>
        <source>WKT</source>
        <translation>WKT (Point, LineString, Polygon)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="200"/>
        <source>Easting Field</source>
        <translation>Easting Field</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="213"/>
        <source>Northing Field</source>
        <translation>Northing Field</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="242"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;a href=&quot;http://giswiki.hsr.ch/Editable_GeoCSV#Help&quot;&gt;&lt;span style=&quot; text-decoration: underline; color:#2b84d3;&quot;&gt;Help&lt;/span&gt;&lt;/a&gt;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation></translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="270"/>
        <source>Convert</source>
        <translation>Convert</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="277"/>
        <source>Character set:</source>
        <translation>Character set:</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="293"/>
        <source>The csv File is not in UTF-8. Please convert it first
 (CAUTION: the original file will be overwritten):</source>
        <translation type="unfinished">The csv file is not UTF-8 encoded. Please convert it first. (CAUTION: The original file will be overwritten!)</translation>
    </message>
</context>
</TS>
