<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_CH">
<context>
    <name>EditableGeoCsv</name>
    <message>
        <location filename="geocsv_plugin.py" line="59"/>
        <source>Add GeoCSV layer</source>
        <translation type="unfinished">GeoCSV Layer hinzufügen</translation>
    </message>
    <message>
        <location filename="geocsv_plugin.py" line="66"/>
        <source>Editable GeoCSV</source>
        <translation type="unfinished">Editable GeoCSV</translation>
    </message>
</context>
<context>
    <name>GeoCsvNewController</name>
    <message>
        <location filename="geocsv_controller.py" line="115"/>
        <source>invalid file path</source>
        <translation type="unfinished">Der angegebene Pfad ist ungültig</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="135"/>
        <source>unknown csvt attribute: {}</source>
        <translation type="unfinished">Ungültiges csvt Attribut: {}</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="137"/>
        <source>csv&lt;-&gt;csvt missmatch</source>
        <translation type="unfinished">Das CSVT-Schema passt nicht zum angegeben CSV-File</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="139"/>
        <source>csvt geometry type exception</source>
        <translation type="unfinished">Falsche Geometrieangaben</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="141"/>
        <source>no csvt file found</source>
        <translation type="unfinished">Kein CSVT-File gefunden</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="165"/>
        <source>error while loading csv</source>
        <translation type="unfinished">Fehler beim laden des CSV-Files</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="155"/>
        <source>error in geometry selection</source>
        <translation type="unfinished">Fehler in den Geometrieangaben</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="75"/>
        <source>GeoCSV Layer created</source>
        <translation type="unfinished">GeoCSV layer erstellt</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="75"/>
        <source>The layer &quot;{}&quot; was created successfully.</source>
        <translation type="unfinished">Der layer &quot;{}&quot; wurde erfolgreich erstellt</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="103"/>
        <source>Open GeoCSV File</source>
        <translation type="unfinished">GeoCSV Dokument öffnen</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="103"/>
        <source>Files (*.csv *.tsv)</source>
        <translation type="unfinished">Dokumente (*.csv *.tsv)</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="261"/>
        <source>CSVT File Error</source>
        <translation type="unfinished">Fehler in CSVT File</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="81"/>
        <source>The csvt file couldn&apos;t be updated on disk.</source>
        <translation type="unfinished">Das CSVT File konnte nicht aktualisiert werden.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="261"/>
        <source>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</source>
        <translation type="unfinished">Fehler beim Aktualisieren des CSVT Files. Bitte aktualisieren Sie das CSVT File manuell.</translation>
    </message>
</context>
<context>
    <name>GeoCsvReconnectController</name>
    <message>
        <location filename="geocsv_controller.py" line="236"/>
        <source>Couldn&apos;t automatically restore csv layer &quot;{}&quot;</source>
        <translation type="unfinished">Fehlende Angaben für den GeoCSV-Layer {}</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="234"/>
        <source>GeoCSV Layer reconnected</source>
        <translation type="unfinished">GeoCSV Layer erfolgreich geladen</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="234"/>
        <source>Layer &quot;{}&quot; is successfully reconnected</source>
        <translation type="unfinished">Der Layer &quot;{}&quot; wurde erfolgreich geladen</translation>
    </message>
</context>
<context>
    <name>VectorLayerController</name>
    <message>
        <location filename="geocsv_controller.py" line="248"/>
        <source>CSV File updated</source>
        <translation type="unfinished">CSV Dokument aktualisiert</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="248"/>
        <source>Changes to layer &quot;{}&quot; successfully stored in csv file.</source>
        <translation type="unfinished">Änderungen im layer &quot;{}&quot; wurden erfolgreich gespeichert. </translation>
    </message>
</context>
<context>
    <name>VectorLayerSaveConflictController</name>
    <message>
        <location filename="geocsv_controller.py" line="312"/>
        <source>Save File</source>
        <translation type="unfinished">Dokument speichern</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="320"/>
        <source>Invalid path</source>
        <translation type="unfinished">Der angegebene Pfad ist ungültig</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="320"/>
        <source>An error occured while trying to save file on new location. Please try again.</source>
        <translation type="unfinished">Beim Versuch, das Dokument am neuen Ort zu speichern, ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="273"/>
        <source>CSVT file could not be updated</source>
        <translation type="unfinished">CSVT Dokument konnte nicht aktualisiert werden</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="273"/>
        <source>An error occured while trying to update the CSVT file according to the new attribute types. Please update the csvt file manually.</source>
        <translation type="unfinished">Fehler beim Aktualisieren des CSVT Files. Bitte aktualisieren Sie das CSVT File manuell.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="268"/>
        <source>Error while updating attributes happend</source>
        <translation type="unfinished">Fehler beim Aktualisieren der Attribute aufgetreten</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="268"/>
        <source>An error occured while trying to update the attributes list. Nothing has been stored on disk.</source>
        <translation type="unfinished">Beim Versuch, die Attributliste zu aktualisieren, ist ein Fehler aufgetreten. Es wurde nichts gespeichert.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="277"/>
        <source>Geometry index violation</source>
        <translation type="unfinished">Fehler in den Geometrie-Angaben</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="277"/>
        <source>You tried to delete an attribute which is providing geometry information. The change will not be saved to disk.</source>
        <translation type="unfinished">Das gelöschte Attribut enthielt Geometrieangaben. Dies kann zu unbestimmten Problemen führen. Bitte verlassen Sie den Editiermodus ohne die Änderungen zu speichern.</translation>
    </message>
    <message>
        <location filename="geocsv_controller.py" line="312"/>
        <source>Files (*.csv *.tsv)</source>
        <translation type="unfinished">Dokumente (*.csv *.tsv)</translation>
    </message>
</context>
<context>
    <name>geocsvDialogNew</name>
    <message>
        <location filename="geocsv_dialog_new.ui" line="14"/>
        <source>GeoCSV Editor</source>
        <translation type="unfinished">Neuer GeoCSV Layer hinzufügen</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="29"/>
        <source>Retry</source>
        <translation type="unfinished">Nochmals versuchen</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="68"/>
        <source>Cancel</source>
        <translation type="unfinished">Abbrechen</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="43"/>
        <source>Save As</source>
        <translation type="unfinished">Speichern unter</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_conflict.ui" line="59"/>
        <source>Error: The csv file could not be saved. File Lock?</source>
        <translation type="unfinished">Die Änderungen konnten nicht ins CSV-File gespeichert werden, da das File nicht gefunden oder gelocked ist. </translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="29"/>
        <source>Dateiname</source>
        <translation type="unfinished">Dateiname</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="46"/>
        <source>Durchsuchen...</source>
        <translation type="unfinished">Durchsuchen...</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="78"/>
        <source>Ok</source>
        <translation type="unfinished">OK</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="122"/>
        <source>WKT Field</source>
        <translation type="unfinished">WKT Feld</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="136"/>
        <source>Point (Easting/Northing)</source>
        <translation type="unfinished">Easting/Northing (Point)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="155"/>
        <source>WKT</source>
        <translation type="unfinished">WKT (Point, LineString, Polygon)</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="200"/>
        <source>Easting Field</source>
        <translation type="unfinished">Easting Feld</translation>
    </message>
    <message>
        <location filename="geocsv_dialog_new.ui" line="213"/>
        <source>Northing Field</source>
        <translation type="unfinished">Northing Feld</translation>
    </message>
</context>
</TS>
